### PR TITLE
Added IP logging, enable by adding logIP option

### PR DESCRIPTION
**Pull request by VottusCode**
As promised in issue #18, I've added the option to log IPs.

### CODE REVIEW

**Comment by sirrodgepodge** [comment]
@VottusCode thank you!

**Comment by VottusCode** [comment]
No problem! I thank you for creating such amazing library! 👍

**Comment by adams-family** [comment]
Hi @VottusCode - thanks!!

BTW I noticed that you added a ',' (comma) in logReqUserAgent (`index.js` line 318) - just checking if that was intentional?

**Comment by VottusCode** [comment]
> Hi @VottusCode - thanks!!
> 
> BTW I noticed that you added a ',' (comma) in logReqUserAgent (`index.js` line 318) - just checking if that was intentional?

yeah 👍

**Pull request merged**
