### PR TITLE
[Work in progress] Transports & Metadata logging

### PR DESCRIPTION
**Pull request by VottusCode**
Hello, today I'd like to present you 2 new features:

1. Transports - Transports are classes that take care of well, transporting the log to some place. Users can create their own transports by creating a class that extends BaseTransport, but there are also premade ones - at the moment it's ConsoleTransport, FileTransport and StreamTransport.

2. Logging Metadata - Let's say you have a middleware, it takes care of identifying an user that's using your app. You pass that data, and there it ends. But what if you want to log that data, so you know who was it that was trying to use your app? With  this new feature, all you have to do is pass all that data to `req.metadata`, and MorganBody will log it! This idea came up from issue #28.

Sincerely,
Vottus

### CODE REVIEW

**Comment by VottusCode** [comment]
I just need to add tests; unfortunetely I don't have enough time right now.

also, @sirrodgepodge, I think it would be nice to add a CI, since you already have tests. I recommend CircleCI.

**Comment by sirrodgepodge** [comment]
@VottusCode good point haha, right now when other people make PRs I've always been writing the tests :)

**Comment by VottusCode** [comment]
I've PRed the CircleCI configuration (#36), it also follows steps how to setup CircleCI on your side.

**Comment by VottusCode** [comment]
@sirrodgepodge I'm really busy with some projects and things IRL, could you find the time to write the tests for Metadata logging?
There's no need to test transports.

**Comment by sirrodgepodge** [comment]
@VottusCode I will try, maybe this weekend

**Comment by sirrodgepodge** [comment]
@VottusCode sounds like you're working on a pretty epic rewrite, still worth me writing tests for this?

**Comment by VottusCode** [comment]
> @VottusCode sounds like you're working on a pretty epic rewrite, still worth me writing tests for this?

No, I will write new tests coming with the rewrite, so it doesn't make sense.

**Comment by VottusCode** [comment]
Closed in favor of #37

**Pull request closed without merging**
